POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "An event for those who are passionate about programming",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/7c4a1307-b678-4356-bfff-c2eff710d5f3/attendees
Content-Type: application/json

{
  "name": "Pedro Matos",
  "email": "pedrohematos@outlook.com"
}

###

GET http://localhost:3333/events/7c4a1307-b678-4356-bfff-c2eff710d5f3

###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/7c4a1307-b678-4356-bfff-c2eff710d5f3/attendees?name=pedro